---
deployment:
  tasks:
    - export DEPLOYPATH=/home/demandsignals/public_html/
    - /bin/cp -R $HOME/repositories/demandsignals-site/css $DEPLOYPATH
    - /bin/cp -R $HOME/repositories/demandsignals-site/js $DEPLOYPATH
    - /bin/cp -R $HOME/repositories/demandsignals-site/assets $DEPLOYPATH
    - /bin/cp -R $HOME/repositories/demandsignals-site/includes $DEPLOYPATH
    - /bin/cp -R $HOME/repositories/demandsignals-site/pages $DEPLOYPATH
    - /bin/cp -R $HOME/repositories/demandsignals-site/api $DEPLOYPATH
    - /bin/cp $HOME/repositories/demandsignals-site/index.php $DEPLOYPATH
    - /bin/cp $HOME/repositories/demandsignals-site/404.php $DEPLOYPATH
    - /bin/cp $HOME/repositories/demandsignals-site/.htaccess $DEPLOYPATH
